import { defineCloudflareConfig } from "@opennextjs/cloudflare";
import staticAssetsIncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/static-assets-incremental-cache";

/**
 * An incremental cache is NOT optional here, despite this site having no ISR.
 *
 * Next treats every route generated by `generateStaticParams` as "prerendered"
 * rather than "static", and OpenNext serves prerendered routes by reading them
 * out of the incremental cache — not from the assets directory. With no cache
 * configured, all 15 `/solutions/[pillar]` and `/solutions/[pillar]/[service]`
 * routes answered 404 with `x-nextjs-prerender: 1, x-nextjs-cache: MISS`: the
 * router knew the page existed and had nowhere to read it from. Plain static
 * routes (/, /about, /contact …) were unaffected, which makes the failure easy
 * to miss if you only spot-check the homepage.
 *
 * `staticAssetsIncrementalCache` is the right backend for this app specifically.
 * Its own docs say it "should only be used for applications that do NOT want
 * revalidation and ONLY want to serve prerendered data" — which is exactly this
 * site: every page is baked at build time and nothing calls `revalidate`. It
 * serves them from the ASSETS binding under `cdn-cgi/_next_cache`, so there is
 * no R2 bucket, no KV namespace, and no per-request cost.
 *
 * If ISR or on-demand revalidation is ever added, this must be swapped for
 * `r2IncrementalCache` (plus a tag cache) — writes are a no-op here.
 */
export default defineCloudflareConfig({
  incrementalCache: staticAssetsIncrementalCache,
});
