/**
 * Privacy Policy — ported from the live policy in content/privacy.md.
 *
 * Prose is the client's existing published policy, restructured into sections
 * and lightly copy-edited (run-together address, broken contact URL). The old
 * `/contact-us/` link did not exist on the site; it now points at `/contact`.
 *
 * Section ids are stable and kebab-case: they are the anchor targets used by the
 * on-page table of contents, so renaming one breaks inbound links.
 */
import type { LegalDoc } from "../types";

export const privacy: LegalDoc = {
  title: "Privacy Policy",
  updated: "2026-08-07",
  intro:
    "This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the Service, and tells you about your privacy rights and how the law protects you. We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.",
  reviewRequired: false,
  sections: [
    {
      id: "interpretation",
      heading: "Interpretation",
      body: [
        "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
      ],
    },
    {
      id: "definitions",
      heading: "Definitions",
      body: [
        "For the purposes of this Privacy Policy:",
        "Account means a unique account created for you to access our Service or parts of our Service.",
        "Affiliate means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.",
        "Company (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to CrossBorder Business Solution, a sole proprietorship at Kandivali-West, Mumbai 400067, India.",
        "Cookies are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.",
        "Country refers to Maharashtra, India.",
        "Device means any device that can access the Service, such as a computer, a cellphone or a digital tablet.",
        "Personal Data is any information that relates to an identified or identifiable individual.",
        "Service refers to the Website.",
        "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.",
        "Third-party Social Media Service refers to any website or any social network website through which a user can log in or create an account to use the Service.",
        "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
        "Website refers to CrossBorder Business Solution, accessible from https://cbbusinesssolution.com/.",
        "You means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
      ],
    },
    {
      id: "personal-data",
      heading: "Personal data we collect",
      body: [
        "While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:",
        "Email address; first name and last name; phone number; address, state, province, ZIP or postal code and city; and usage data.",
      ],
    },
    {
      id: "usage-data",
      heading: "Usage data",
      body: [
        "Usage data is collected automatically when using the Service.",
        "Usage data may include information such as your device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
        "When you access the Service by or through a mobile device, we may collect certain information automatically, including but not limited to the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile internet browser you use, unique device identifiers and other diagnostic data.",
      ],
    },
    {
      id: "third-party-social-media",
      heading: "Information from third-party social media services",
      body: [
        "The Company allows you to create an account and log in to use the Service through the following third-party social media services: Google, Facebook, Instagram, Twitter and LinkedIn.",
        "If you decide to register through, or otherwise grant us access to, a third-party social media service, we may collect personal data that is already associated with that account, such as your name, your email address, your activities or your contact list associated with that account.",
      ],
    },
    {
      id: "use-of-personal-data",
      heading: "How we use your personal data",
      body: [
        "The Company may use personal data for the following purposes:",
        "To provide and maintain our Service, including to monitor the usage of our Service.",
        "To manage your account: to manage your registration as a user of the Service. The personal data you provide can give you access to different functionalities of the Service that are available to you as a registered user.",
        "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased, or of any other contract with us through the Service.",
        "To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including security updates, when necessary or reasonable for their implementation.",
        "To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those you have already purchased or enquired about, unless you have opted not to receive such information.",
        "To manage your requests: to attend to and manage your requests to us.",
        "For business transfers: we may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets.",
        "For other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, services, marketing and your experience.",
      ],
    },
    {
      id: "data-security",
      heading: "Security of your personal data",
      body: [
        "The security of your personal data is important to us, but remember that no method of transmission over the internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.",
      ],
    },
    {
      id: "delete-your-data",
      heading: "Deleting your personal data",
      body: [
        "You have the right to delete, or to request that we assist in deleting, the personal data that we have collected about you. Our Service may give you the ability to delete certain information about you from within the Service.",
        "You may also contact us to request access to, correction of, or deletion of any personal data you have provided to us.",
      ],
    },
    {
      id: "childrens-privacy",
      heading: "Children's privacy",
      body: [
        "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us.",
        "If we become aware that we have collected personal data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.",
      ],
    },
    {
      id: "changes-to-this-policy",
      heading: "Changes to this policy",
      body: [
        "We may update this policy from time to time. Please review it periodically.",
        "This Privacy Policy is effective as of 2 August 2025 and was last updated on 7 August 2026.",
      ],
    },
    {
      id: "contact-us",
      heading: "Contact us",
      body: [
        "If you have any questions about this Privacy Policy, you can contact us by email at support@cbbusinesssolution.com.",
        "You can also reach us through our contact page at /contact, or by post at Kandivali-West, Mumbai 400067, India.",
      ],
    },
  ],
  seo: {
    title: "Privacy Policy",
    description:
      "How CrossBorder Business Solution collects, uses, stores and deletes personal data on cbbusinesssolution.com, and how to exercise your privacy rights.",
  },
};
